import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="valentine" className="scroll-smooth">
      {/* include all the other pages, can add reusable component in this file */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
